## LOADING THE DATASET

In [ ]:
import pandas as pd

In [ ]:
train_data = pd.read_csv('/content/drive/MyDrive/aepr/aepr_45k_train.csv') # , index_col=0
test_data = pd.read_csv('/content/drive/MyDrive/aepr/aepr_45k_test.csv') # , index_col=0

## Analysing the data

In [ ]:
print(train_data.columns)

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='object')

In [ ]:
print(train_data.shape)

(45593, 20)

In [ ]:
train_data.dtypes

ID                              object
Delivery_person_ID              object
Delivery_person_Age             object
Delivery_person_Ratings         object
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weatherconditions               object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries             object
Festival                        object
City                            object
Time_taken(min)                 object
dtype: object

In [ ]:
# data = pd.concat([train_data.drop(['Delivery_person_ID',
#                  'Delivery_person_Age',
#                  'Delivery_person_Ratings',
#                  'Weatherconditions',
#                  'Road_traffic_density',
#                  'Vehicle_condition',
#                  'Type_of_order',
#                  'Type_of_vehicle',
#                  'multiple_deliveries',
#                  'Festival',
#                  'City',
#                  'Time_taken(min)'], axis=1),

# test_data.drop(['Delivery_person_ID',
#                  'Delivery_person_Age',
#                  'Delivery_person_Ratings',
#                  'Weatherconditions',
#                  'Road_traffic_density',
#                  'Vehicle_condition',
#                  'Type_of_order',
#                  'Type_of_vehicle',
#                  'multiple_deliveries',
#                  'Festival',
#                  'City'], axis=1)], ignore_index=True)

In [ ]:
data = train_data.drop(['Delivery_person_ID',
                 'Delivery_person_Age',
                 'Delivery_person_Ratings',
                 'Weatherconditions',
                 'Road_traffic_density',
                 'Vehicle_condition',
                 'Type_of_order',
                 'Type_of_vehicle',
                 'multiple_deliveries',
                 'Festival',
                 'City'], axis=1)

In [ ]:
set(train_data['City']).union(set(test_data['City']))

{'Metropolitian ', 'NaN ', 'Semi-Urban ', 'Urban '}

In [ ]:
# x = 'ID'
# x = 'Delivery_person_ID'
x = 'Order_Date'
set(train_data[x]).union(set(test_data[x]))
print(len(set(train_data[x]).union(set(test_data[x]))))

44

In [ ]:
for x in train_data.columns:
  print(x,end='\t')
  if x != 'Time_taken(min)':
    print(len(set(train_data[x]).union(set(test_data[x]))))
  else:
    print(len(set(train_data[x])))

ID	56992
Delivery_person_ID	1320
Delivery_person_Age	23
Delivery_person_Ratings	29
Restaurant_latitude	689
Restaurant_longitude	546
Delivery_location_latitude	4375
Delivery_location_longitude	4375
Order_Date	44
Time_Orderd	177
Time_Order_picked	193
Weatherconditions	7
Road_traffic_density	5
Vehicle_condition	4
Type_of_order	4
Type_of_vehicle	4
multiple_deliveries	5
Festival	3
City	4
Time_taken(min)	45

In [ ]:
print(test_data.columns)

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City'],
      dtype='object')

In [ ]:
print(test_data.shape)

(11399, 19)

In [ ]:
train_data.describe()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition
count,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000
mean,17.017729,70.231332,17.465186,70.845702,1.023359
std,8.185109,22.883647,7.335122,21.118812,0.839065
min,-30.905562,-88.366217,0.010000,0.010000,0.000000
25%,12.933284,73.170000,12.988453,73.280000,0.000000
50%,18.546947,75.898497,18.633934,76.002574,1.000000
75%,22.728163,78.044095,22.785049,78.107044,2.000000
max,30.914057,88.433452,31.054057,88.563452,3.000000

In [ ]:
45593.000000	+ 11399.000000

56992.0

In [ ]:
test_data.describe()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition
count,11399.000000,11399.000000,11399.000000,11399.000000,11399.000000
mean,17.099934,70.399259,17.569497,71.102187,1.031406
std,8.193510,22.773144,7.287440,20.693782,0.839599
min,-30.902872,-88.400467,0.010000,0.010000,0.000000
25%,12.933284,73.170937,12.992532,73.771081,0.000000
50%,18.551440,75.897429,18.643481,75.996959,1.000000
75%,22.732225,78.045732,22.791226,78.109004,2.000000
max,30.914057,88.433452,31.054057,88.563452,3.000000

In [ ]:
# FINAL DATA
# data = pd.concat([train_data, test_data])

In [ ]:
data.shape

(45593, 9)

In [ ]:
data.columns

Index(['ID', 'Restaurant_latitude', 'Restaurant_longitude',
       'Delivery_location_latitude', 'Delivery_location_longitude',
       'Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Time_taken(min)'],
      dtype='object')

In [ ]:
data.describe()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude
count,45593.000000,45593.000000,45593.000000,45593.000000
mean,17.017729,70.231332,17.465186,70.845702
std,8.185109,22.883647,7.335122,21.118812
min,-30.905562,-88.366217,0.010000,0.010000
25%,12.933284,73.170000,12.988453,73.280000
50%,18.546947,75.898497,18.633934,76.002574
75%,22.728163,78.044095,22.785049,78.107044
max,30.914057,88.433452,31.054057,88.563452

In [ ]:
data.columns

Index(['ID', 'Restaurant_latitude', 'Restaurant_longitude',
       'Delivery_location_latitude', 'Delivery_location_longitude',
       'Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Time_taken(min)'],
      dtype='object')

In [ ]:
train_data

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45588,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,conditions Windy,High,1,Meal,motorcycle,0,No,Metropolitian,(min) 32
45589,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,conditions Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,(min) 36
45590,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,conditions Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,(min) 16
45591,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,conditions Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,(min) 26
45592,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,conditions Fog,Medium,2,Snack,scooter,1,No,Metropolitian,(min) 36

In [ ]:
test_data

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
0,0x2318,COIMBRES13DEL01,NaN,NaN,11.003669,76.976494,11.043669,77.016494,30-03-2022,NaN,15:05:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian
1,0x3474,BANGRES15DEL01,28,4.6,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,0,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,4.5,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,0,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,4.8,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,1,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,4.6,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,2,Drinks,scooter,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11394,0x6909,JAPRES01DEL01,35,4.6,26.905190,75.810753,27.015190,75.920753,27-03-2022,21:35:00,21:45:00,conditions Sunny,Jam,1,Snack,scooter,1,No,Metropolitian
11395,0x443b,JAPRES11DEL01,33,4.9,26.902940,75.793007,26.912940,75.803007,11-03-2022,11:40:00,11:45:00,conditions Sandstorms,High,1,Drinks,scooter,1,No,Metropolitian
11396,0x1ea5,SURRES11DEL03,NaN,NaN,21.157735,72.768778,21.217735,72.828778,11-03-2022,NaN,21:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian
11397,0x22d4,VADRES03DEL02,27,4.7,22.320000,73.170000,22.450000,73.300000,06-03-2022,18:35:00,18:40:00,conditions Sandstorms,Medium,0,Meal,motorcycle,0,No,Metropolitian
11398,0xb7be,CHENRES07DEL02,39,5,13.081878,80.248519,13.131878,80.298519,24-03-2022,22:20:00,22:25:00,conditions Windy,Low,2,Drinks,motorcycle,1,No,Urban

### Finding out the maximum number of orders that are online simultaneously?

In [ ]:
(data.describe())

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude
count,45593.000000,45593.000000,45593.000000,45593.000000
mean,17.017729,70.231332,17.465186,70.845702
std,8.185109,22.883647,7.335122,21.118812
min,-30.905562,-88.366217,0.010000,0.010000
25%,12.933284,73.170000,12.988453,73.280000
50%,18.546947,75.898497,18.633934,76.002574
75%,22.728163,78.044095,22.785049,78.107044
max,30.914057,88.433452,31.054057,88.563452

In [ ]:
data

,ID,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Time_taken(min)
0,0x4607,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,(min) 24
1,0xb379,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,(min) 33
2,0x5d6d,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,(min) 26
3,0x7a6a,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,(min) 21
4,0x70a2,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,(min) 30
...,...,...,...,...,...,...,...,...,...
45588,0x7c09,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,(min) 32
45589,0xd641,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,(min) 36
45590,0x4f8d,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,(min) 16
45591,0x5eee,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,(min) 26
45592,0x5fb2,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,(min) 36

In [ ]:
# data.drop(data.index[56989], inplace=True)

In [ ]:
data

,ID,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Time_taken(min)
0,0x4607,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,(min) 24
1,0xb379,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,(min) 33
2,0x5d6d,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,(min) 26
3,0x7a6a,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,(min) 21
4,0x70a2,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,(min) 30
...,...,...,...,...,...,...,...,...,...
45588,0x7c09,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,(min) 32
45589,0xd641,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,(min) 36
45590,0x4f8d,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,(min) 16
45591,0x5eee,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,(min) 26
45592,0x5fb2,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,(min) 36

In [ ]:
x,y=0,5
print((data.iloc[x,y]))
print(type(data.iloc[x,y]))

19-03-2022
<class 'str'>

In [ ]:
data.dtypes

ID                              object
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Time_taken(min)                 object
dtype: object

### Creating Datetime columns for order_place and order_pick

In [ ]:
# YE SAARA FLOP HO GYA

In [ ]:
from datetime import datetime

In [ ]:
data['order_pick'] = '0'
data['order_place'] = '0'

In [ ]:
# data.iloc[0,8] = 17

In [ ]:
# %timeit pd.to_datetime(df['date'], infer_datetime_format=True)
# df['date'] = pd.to_datetime(df['date'], format="%Y-%d-%m %H:%M:%S")
# Order_Date	Time_Orderd	Time_Order_picked

In [ ]:
# REMOVING ROWS THAT HAVE NaN AS ONE OF THE ENTRIES IN ORDER_DATE OR TIME_ORDERED OR TIME_ORDER_PICKED
# if data.iloc[56989,6] == NaN:
#   print('Yes')
# else:
#   print("No")

# print(data.iloc[56989,6])
# print(data.iloc[56989,6] == "NaN ")

# a = data.iloc[56989,6]

i = 0
while(i<len(data)):
  if "NaN" in data.iloc[i,5] or "NaN" in data.iloc[i,6] or "NaN" in data.iloc[i,7]:
    data.drop(data.index[i], inplace=True)
  else:
    i += 1

In [ ]:
data['order_place'] = pd.to_datetime(data['Order_Date']+' '+data['Time_Orderd'], format="%d-%m-%Y %H:%M:%S", infer_datetime_format=True)

In [ ]:
# for i in range(len(data)):
#   x = data.iloc[i,5].split('-')
#   y = data.iloc[i,6].split(':')
#   z = data.iloc[i,7].split(':')

#   data.iloc[i,9] = datetime(x[2],x[1],x[0],y[0],y[1],y[2])
#   data.iloc[i,8] = datetime(x[2],x[1],x[0],z[0],z[1],z[2])

data['order_pick'] = pd.to_datetime(data['Order_Date']+' '+data['Time_Order_picked'], format="%d-%m-%Y %H:%M:%S", infer_datetime_format=True)

In [ ]:
len(data)

43862

In [ ]:
type(data['order_place'])

pandas.core.series.Series

In [ ]:
# CONTINUE HERE, REINDEX THE DATAFRAME, AND THEN JUST CONFIRM WHETHER THIS IS TRUE OR NOT
count = 0

for i in range(len(data)):
  if data['order_place'][0] > data['order_pick'][0]:
    print(i)
  else:
    count += 1

print(count)

43862

In [ ]:
data = data.reset_index(drop=True)

In [ ]:
data

,ID,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Time_taken(min),order_pick,order_place,order_delivered
0,0x4607,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,24,2022-03-19 11:45:00,2022-03-19 11:30:00,2022-03-19 12:30:00
1,0xb379,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,33,2022-03-25 19:50:00,2022-03-25 19:45:00,2022-03-25 20:35:00
2,0x5d6d,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,26,2022-03-19 08:45:00,2022-03-19 08:30:00,2022-03-19 09:30:00
3,0x7a6a,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,21,2022-04-05 18:10:00,2022-04-05 18:00:00,2022-04-05 18:55:00
4,0x70a2,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,30,2022-03-26 13:45:00,2022-03-26 13:30:00,2022-03-26 14:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...
43857,0x7c09,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,32,2022-03-24 11:45:00,2022-03-24 11:35:00,2022-03-24 12:30:00
43858,0xd641,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,36,2022-02-16 20:10:00,2022-02-16 19:55:00,2022-02-16 20:55:00
43859,0x4f8d,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,16,2022-03-11 00:05:00,2022-03-11 23:50:00,2022-03-11 00:50:00
43860,0x5eee,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,26,2022-03-07 13:40:00,2022-03-07 13:35:00,2022-03-07 14:25:00
43861,0x5fb2,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,36,2022-03-02 17:15:00,2022-03-02 17:10:00,2022-03-02 18:00:00

In [ ]:
type(data['order_pick'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
pd.Timedelta(minutes=45)

Timedelta('0 days 00:45:00')

In [ ]:
print(data['order_pick'][0])
print(data['order_pick'][0] + pd.Timedelta(minutes=45))

2022-03-19 11:45:00
2022-03-19 12:30:00

In [ ]:
for i in range(len(data['Time_taken(min)'])):
  if data['Time_taken(min)'][i] == 17:
    print(i)

In [ ]:
for i in range(len(data['Time_taken(min)'])):
  data['Time_taken(min)'][i] = int(data['Time_taken(min)'][i].split(' ')[1])

<ipython-input-149-c96074af0294>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Time_taken(min)'][i] = int(data['Time_taken(min)'][i].split(' ')[1])

In [ ]:
'as sd'.split(' ')

['as', 'sd']

In [ ]:
x = set(data['Time_taken(min)'])
for i in range(10,55):
  if i not in x:
    print(i)

In [ ]:
data['order_delivered'] = data['order_pick'] + pd.Timedelta(minutes=45)

In [ ]:
import geopy

In [ ]:
data.iloc[0,:]

ID                                         0x4607
Restaurant_latitude                      22.745049
Restaurant_longitude                     75.892471
Delivery_location_latitude               22.765049
Delivery_location_longitude              75.912471
Order_Date                              19-03-2022
Time_Orderd                               11:30:00
Time_Order_picked                         11:45:00
Time_taken(min)                                 17
order_pick                     2022-03-19 11:45:00
order_place                    2022-03-19 11:30:00
Name: 0, dtype: object

In [ ]:
17 in set(data['Time_taken(min)'])

False

In [ ]:
data.to_pickle('/content/drive/MyDrive/aepr/data_preprocessed.pkl')

# NOW LET'S START MAKING GRAPHS

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_pickle('/content/drive/MyDrive/aepr/data_preprocessed.pkl')

In [ ]:
data.sort_values(by='order_place', axis=0, ascending=True, inplace=True, kind='quicksort', na_position='last')

In [ ]:
data

,ID,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Time_taken(min),order_pick,order_place,order_delivered
28451,0xd300,9.970717,76.285447,10.030717,76.345447,11-02-2022,00:00:00,00:05:00,27,2022-02-11 00:05:00,2022-02-11 00:00:00,2022-02-11 00:50:00
35945,0xc614,30.340722,78.060221,30.370722,78.090221,11-02-2022,00:00:00,00:10:00,11,2022-02-11 00:10:00,2022-02-11 00:00:00,2022-02-11 00:55:00
584,0xd152,23.234249,77.434007,23.294249,77.494007,11-02-2022,00:00:00,00:10:00,17,2022-02-11 00:10:00,2022-02-11 00:00:00,2022-02-11 00:55:00
23179,0xc401,30.893081,75.821495,30.943081,75.871495,11-02-2022,00:00:00,00:05:00,12,2022-02-11 00:05:00,2022-02-11 00:00:00,2022-02-11 00:50:00
17845,0xcb30,27.160934,78.044095,27.170934,78.054095,11-02-2022,08:10:00,08:20:00,27,2022-02-11 08:20:00,2022-02-11 08:10:00,2022-02-11 09:05:00
...,...,...,...,...,...,...,...,...,...,...,...,...
23374,0xb7ff,12.978453,77.643685,13.088453,77.753685,06-04-2022,23:55:00,00:00:00,40,2022-04-06 00:00:00,2022-04-06 23:55:00,2022-04-06 00:45:00
1513,0x98f1,21.175975,72.795503,21.255975,72.875503,06-04-2022,23:55:00,00:05:00,35,2022-04-06 00:05:00,2022-04-06 23:55:00,2022-04-06 00:50:00
32749,0x6b08,13.026279,80.174568,13.096279,80.244568,06-04-2022,23:55:00,00:00:00,42,2022-04-06 00:00:00,2022-04-06 23:55:00,2022-04-06 00:45:00
1288,0x2b59,12.986047,80.218114,13.076047,80.308114,06-04-2022,23:55:00,00:05:00,43,2022-04-06 00:05:00,2022-04-06 23:55:00,2022-04-06 00:50:00
29162,0x8b6f,12.284747,76.625861,12.364747,76.705861,06-04-2022,23:55:00,00:00:00,24,2022-04-06 00:00:00,2022-04-06 23:55:00,2022-04-06 00:45:00

In [ ]:
for i in data.columns:
  print(i)
  print(data[i][0])
  print(type(data[i][0]))
  print()

ID
0x4607
<class 'str'>

Restaurant_latitude
22.745049
<class 'numpy.float64'>

Restaurant_longitude
75.892471
<class 'numpy.float64'>

Delivery_location_latitude
22.765049
<class 'numpy.float64'>

Delivery_location_longitude
75.912471
<class 'numpy.float64'>

Order_Date
19-03-2022
<class 'str'>

Time_Orderd
11:30:00
<class 'str'>

Time_Order_picked
11:45:00
<class 'str'>

Time_taken(min)
24
<class 'int'>

order_pick
2022-03-19 11:45:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

order_place
2022-03-19 11:30:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

order_delivered
2022-03-19 12:30:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [ ]:
import geopy.distance

coords_1 = (52.2296756, 21.0122287)
coords_2 = (52.406374, 16.9251681)

print(geopy.distance.geodesic(coords_1, coords_2).km)

279.35290160430094

In [ ]:
def dist(lat1, long1, lat2, long2):
  # returns the distance between two points by 
  # shortest distance on surface of earth
  return geopy.distance.geodesic((lat1, long1), (lat2, long2)).km

In [ ]:
def man_dist(lat1, long1, lat2, long2):
  return dist(lat1, long1, lat2, long1) + dist(lat2, long1, lat2, long2)

In [ ]:
dist(0,90,0,-90)

20003.931458625444

In [ ]:
man_dist(0,90,0,-90)

20003.931458625444

In [ ]:
max_lat = max(data['Restaurant_latitude'].max(), data['Delivery_location_latitude'].max())
min_lat = min(data['Restaurant_latitude'].min(), data['Delivery_location_latitude'].min())

max_long = max(data['Restaurant_longitude'].max(), data['Delivery_location_longitude'].max())
min_long = min(data['Restaurant_longitude'].min(), data['Delivery_location_longitude'].min())

In [ ]:
print(max_lat, min_lat, max_long, min_long)

31.054057 -30.902872 88.563452 0.0

In [ ]:
# sorted(list(set(data['Order_Date']))) # we have records from 1 march, 2022, to 6 Apr 2022

In [ ]:
# SIMULATION PARAMETERS
MAX_LAT = max(data['Restaurant_latitude'].max(), data['Delivery_location_latitude'].max())
MIN_LAT = min(data['Restaurant_latitude'].min(), data['Delivery_location_latitude'].min())

MAX_LONG = max(data['Restaurant_longitude'].max(), data['Delivery_location_longitude'].max())
MIN_LONG = min(data['Restaurant_longitude'].min(), data['Delivery_location_longitude'].min())

NUM_BOYS = 50
NUM_BOYS_PER_RESTRO = 5
BIKE_SPEED = 40

In [ ]:
# random.randrange(10001)

In [ ]:
from random import randrange
boys = []

for i in range(NUM_BOYS):
  boys.append({'lat':randrange(10001), 'long':randrange(10001)})

for i in range(NUM_BOYS):
  boys[i]['lat'] = MIN_LAT + (MAX_LAT - MIN_LAT)*boys[i]['lat']/10000
  boys[i]['long'] = MIN_LONG + (MAX_LONG - MIN_LONG)*boys[i]['long']/10000

In [ ]:
boys

[{'lat': -9.6082755027, 'long': 55.3610138452},
 {'lat': 24.69108039170001, 'long': 62.7117803612},
 {'lat': 19.7593088433, 'long': 18.341490909199997},
 {'lat': 24.560970840800007, 'long': 28.597138650799998},
 {'lat': 30.192855686900007, 'long': 20.962969088399998},
 {'lat': -22.7059702933, 'long': 10.0873771828},
 {'lat': 19.350393111900008, 'long': 53.501181353199996},
 {'lat': 2.938002619800006, 'long': 77.1653357276},
 {'lat': -21.3491135482, 'long': 44.1311681316},
 {'lat': -8.2514187576, 'long': 30.9440701288},
 {'lat': -5.946620998799997, 'long': 88.2446235728},
 {'lat': -17.6936547372, 'long': 39.711851876800004},
 {'lat': 19.883222701300003, 'long': 74.39329968},
 {'lat': 22.101280759500003, 'long': 5.366945191199999},
 {'lat': 21.388776076000003, 'long': 58.930120960800004},
 {'lat': -15.072876640499999, 'long': 4.959553312},
 {'lat': -25.413488090599998, 'long': 84.2061301616},
 {'lat': -7.086628492399996, 'long': 0.8590654844000001},
 {'lat': -6.553798902999997, 'long': 31.068058961600002},
 {'lat': -18.2822455627, 'long': 12.8328441948},
 {'lat': 4.988776969700002, 'long': 46.3275417412},
 {'lat': 20.409856597800005, 'long': 79.70710679999999},
 {'lat': -6.082926242599999, 'long': 68.9555037272},
 {'lat': -2.7496434624000017, 'long': 12.088911198},
 {'lat': -2.402684660000002, 'long': 48.603622457600004},
 {'lat': -6.857387855099997, 'long': 59.70062299319999},
 {'lat': -6.454667816599997, 'long': 32.9278914536},
 {'lat': 7.4546627439000055, 'long': 27.472382810400003},
 {'lat': -19.484209985299998, 'long': 86.49106722319999},
 {'lat': 30.5769886467, 'long': 74.2073164308},
 {'lat': 17.566033556700003, 'long': 71.21387175320001},
 {'lat': -0.7546303485999957, 'long': 83.2319321896},
 {'lat': -0.5439767899999985, 'long': 21.910598024800002},
 {'lat': -14.942767089599998, 'long': 77.51958953559999},
 {'lat': -21.7642249725, 'long': 55.998670699600005},
 {'lat': 20.787793864700003, 'long': 55.157317905599996},
 {'lat': 4.592252624100002, 'long': 73.2685438396},
 {'lat': -6.665321375199998, 'long': 77.82070527239999},
 {'lat': -29.434492782699998, 'long': 8.1655502744},
 {'lat': 25.824892192400004, 'long': 33.6186863792},
 {'lat': -20.7233485653, 'long': 75.8811656736},
 {'lat': 28.5943669187, 'long': 19.926776699999998},
 {'lat': -3.9516078850000014, 'long': 5.8540441772},
 {'lat': 12.101432418900007, 'long': 4.7735700628},
 {'lat': 9.499241400900008, 'long': 4.6850066107999995},
 {'lat': -21.987269916899997, 'long': 35.115408718},
 {'lat': 6.3642207934999995, 'long': 0.5668060927999999},
 {'lat': 18.0307105242, 'long': 61.347903200400005},
 {'lat': -9.998604155399999, 'long': 48.399926518},
 {'lat': -19.1124684113, 'long': 35.558225977999996}]

# TRYING OUT SIMPY

In [ ]:
%pip install simpy
import simpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: simpy in /usr/local/lib/python3.10/dist-packages (4.0.1)

In [ ]:
# dir(simpy)

In [ ]:
def func():
  a = [1,2,3,4,5]
  for i in a:
    yield i

In [ ]:
for i in func():
  print(i)

1
2
3
4
5

In [ ]:
def car(env):
  while(True):
    print(f'Start parking at {env.now}')
    parking_duration = 5
    yield env.timeout(parking_duration)

    print(f'Start driving at {env.now}')
    trip_duration = 2
    yield env.timeout(trip_duration)

In [ ]:
import simpy
env = simpy.Environment()

In [ ]:
env.process(car(env))

In [ ]:
env.run(until=15)

Start parking at 0
Start driving at 5
Start parking at 7
Start driving at 12
Start parking at 14

In [ ]:
index = 0
arr = [1,2,3,4,5]

In [ ]:
def f():
  '''
  this is a sample function
  '''
  global index
  global arr
  print(arr[index])
  index += 1

for i in range(5):
  f()

1
2
3
4
5

In [ ]:
help(f)

Help on function f in module __main__:

f()
    this is a sample function

# CREATING SAMPLE SIMPY CODES

In [ ]:
import simpy

In [ ]:
env = simpy.Environment()

In [ ]:
help(env.run)

Help on method run in module simpy.core:

run(until: Union[int, float, simpy.events.Event, NoneType] = None) -> Optional[Any] method of simpy.core.Environment instance
    Executes :meth:`step()` until the given criterion *until* is met.

    - If it is ``None`` (which is the default), this method will return
      when there are no further events to be processed.

    - If it is an :class:`~simpy.events.Event`, the method will continue
      stepping until this event has been triggered and will return its
      value.  Raises a :exc:`RuntimeError` if there are no further events
      to be processed and the *until* event was not triggered.

    - If it is a number, the method will continue stepping
      until the environment's time reaches *until*.

# RUNNING CHAT GPT EXAMPLE CODE 1

In [ ]:
import simpy
import random

GAS_STATION_SIZE = 2  # Number of refill points
TANK_SIZE = 40  # Size of car's fuel tank
# REFUEL_SPEED = 2  # Litres of fuel per second
REFUEL_SPEED = 8  # Litres of fuel per second
ARRIVAL_INTERVAL = 5  # Time between car arrivals
SIM_TIME = 100  # Simulation time in seconds

def car(env, name, gas_station, fuel_pump):
    print(f'\n{name} enters the gas station at {env.now:.2f}')
    with gas_station.request() as req:
        yield req

        print(f'{name} starts refueling at {env.now:.2f}')

        # ye wali line panga kar deti hai
        yield fuel_pump.get(TANK_SIZE)

        yield env.timeout(TANK_SIZE / REFUEL_SPEED)
        print(f'{name} finishes refueling at {env.now:.2f}')

    print(f'{name} exits the gas station at {env.now:.2f}')

def car_generator(env, gas_station, fuel_pump):
    count = 0
    while True:
        yield env.timeout(random.expovariate(1/ARRIVAL_INTERVAL))
        count += 1
        env.process(car(env, f'Car {count}', gas_station, fuel_pump))

# Create the SimPy environment
env = simpy.Environment()

# Create the gas station and fuel pumps
gas_station = simpy.Resource(env, capacity=GAS_STATION_SIZE)
fuel_pump = simpy.Container(env, init=GAS_STATION_SIZE*TANK_SIZE, capacity=GAS_STATION_SIZE*TANK_SIZE)

# Start the simulation
env.process(car_generator(env, gas_station, fuel_pump))

In [ ]:
env.run(until=SIM_TIME)

Car 1 enters the gas station at 3.12
Car 1 starts refueling at 3.12

Car 2 enters the gas station at 4.68
Car 2 starts refueling at 4.68
Car 1 finishes refueling at 8.12
Car 1 exits the gas station at 8.12
Car 2 finishes refueling at 9.68
Car 2 exits the gas station at 9.68

Car 3 enters the gas station at 17.15
Car 3 starts refueling at 17.15

Car 4 enters the gas station at 17.67
Car 4 starts refueling at 17.67

Car 5 enters the gas station at 19.76
Car 3 finishes refueling at 22.15
Car 3 exits the gas station at 22.15
Car 5 starts refueling at 22.15
Car 4 finishes refueling at 22.67
Car 4 exits the gas station at 22.67
Car 5 finishes refueling at 27.15
Car 5 exits the gas station at 27.15

Car 6 enters the gas station at 40.87
Car 6 starts refueling at 40.87

Car 7 enters the gas station at 42.64
Car 7 starts refueling at 42.64

Car 8 enters the gas station at 44.53
Car 6 finishes refueling at 45.87
Car 6 exits the gas station at 45.87
Car 8 starts refueling at 45.87
Car 7 finishes refueling at 47.64
Car 7 exits the gas station at 47.64

Car 9 enters the gas station at 48.57
Car 9 starts refueling at 48.57
Car 8 finishes refueling at 50.87
Car 8 exits the gas station at 50.87
Car 9 finishes refueling at 53.57
Car 9 exits the gas station at 53.57

Car 10 enters the gas station at 54.49
Car 10 starts refueling at 54.49

Car 11 enters the gas station at 55.33
Car 11 starts refueling at 55.33

Car 12 enters the gas station at 55.44

Car 13 enters the gas station at 58.19
Car 10 finishes refueling at 59.49
Car 10 exits the gas station at 59.49
Car 12 starts refueling at 59.49
Car 11 finishes refueling at 60.33
Car 11 exits the gas station at 60.33
Car 13 starts refueling at 60.33
Car 12 finishes refueling at 64.49
Car 12 exits the gas station at 64.49
Car 13 finishes refueling at 65.33
Car 13 exits the gas station at 65.33

Car 14 enters the gas station at 71.29
Car 14 starts refueling at 71.29

Car 15 enters the gas station at 75.72
Car 15 starts refueling at 75.72
Car 14 finishes refueling at 76.29
Car 14 exits the gas station at 76.29
Car 15 finishes refueling at 80.72
Car 15 exits the gas station at 80.72

Car 16 enters the gas station at 84.06
Car 16 starts refueling at 84.06
Car 16 finishes refueling at 89.06
Car 16 exits the gas station at 89.06

Car 17 enters the gas station at 95.66
Car 17 starts refueling at 95.66

In [ ]:
env.run()

Streaming output truncated to the last 5000 lines.
Car 15585 enters the gas station at 77742.72

Car 15586 enters the gas station at 77747.48

Car 15587 enters the gas station at 77749.56

Car 15588 enters the gas station at 77755.07

Car 15589 enters the gas station at 77761.71

Car 15590 enters the gas station at 77761.84

Car 15591 enters the gas station at 77767.37

Car 15592 enters the gas station at 77768.20

Car 15593 enters the gas station at 77771.50

Car 15594 enters the gas station at 77773.30

Car 15595 enters the gas station at 77774.20

Car 15596 enters the gas station at 77778.66

Car 15597 enters the gas station at 77780.12

Car 15598 enters the gas station at 77790.88

Car 15599 enters the gas station at 77805.13

Car 15600 enters the gas station at 77807.37

Car 15601 enters the gas station at 77812.82

Car 15602 enters the gas station at 77813.29

Car 15603 enters the gas station at 77823.85

Car 15604 enters the gas station at 77832.16

Car 15605 enters the gas station at 77835.26

Car 15606 enters the gas station at 77837.63

Car 15607 enters the gas station at 77839.97

Car 15608 enters the gas station at 77853.42

Car 15609 enters the gas station at 77865.48

Car 15610 enters the gas station at 77869.78

Car 15611 enters the gas station at 77871.47

Car 15612 enters the gas station at 77872.32

Car 15613 enters the gas station at 77878.52

Car 15614 enters the gas station at 77878.58

Car 15615 enters the gas station at 77881.93

Car 15616 enters the gas station at 77884.62

Car 15617 enters the gas station at 77891.08

Car 15618 enters the gas station at 77898.84

Car 15619 enters the gas station at 77899.75

Car 15620 enters the gas station at 77904.80

Car 15621 enters the gas station at 77908.20

Car 15622 enters the gas station at 77915.52

Car 15623 enters the gas station at 77916.45

Car 15624 enters the gas station at 77923.53

Car 15625 enters the gas station at 77947.32

Car 15626 enters the gas station at 77952.74

Car 15627 enters the gas station at 77956.16

Car 15628 enters the gas station at 77961.38

Car 15629 enters the gas station at 77975.68

Car 15630 enters the gas station at 77977.87

Car 15631 enters the gas station at 77978.25

Car 15632 enters the gas station at 78001.38

Car 15633 enters the gas station at 78003.19

Car 15634 enters the gas station at 78019.78

Car 15635 enters the gas station at 78022.29

Car 15636 enters the gas station at 78036.91

Car 15637 enters the gas station at 78046.27

Car 15638 enters the gas station at 78056.00

Car 15639 enters the gas station at 78058.80

Car 15640 enters the gas station at 78074.46

Car 15641 enters the gas station at 78074.89

Car 15642 enters the gas station at 78075.16

Car 15643 enters the gas station at 78075.47

Car 15644 enters the gas station at 78076.69

Car 15645 enters the gas station at 78078.02

Car 15646 enters the gas station at 78079.34

Car 15647 enters the gas station at 78095.86

Car 15648 enters the gas station at 78106.22

Car 15649 enters the gas station at 78110.61

Car 15650 enters the gas station at 78112.28

Car 15651 enters the gas station at 78114.83

Car 15652 enters the gas station at 78129.76

Car 15653 enters the gas station at 78130.27

Car 15654 enters the gas station at 78152.37

Car 15655 enters the gas station at 78153.69

Car 15656 enters the gas station at 78161.21

Car 15657 enters the gas station at 78165.00

Car 15658 enters the gas station at 78166.20

Car 15659 enters the gas station at 78167.91

Car 15660 enters the gas station at 78173.84

Car 15661 enters the gas station at 78178.75

Car 15662 enters the gas station at 78190.25

Car 15663 enters the gas station at 78192.30

Car 15664 enters the gas station at 78194.93

Car 15665 enters the gas station at 78196.24

Car 15666 enters the gas station at 78198.72

Car 15667 enters the gas station at 78210.73

Car 15668 enters the gas station at 78212.80

Car 15669 enters the gas station at 78219.78

Car 15670 enters the gas station at 78224.33

Car 15671 enters the gas station at 78230.98

Car 15672 enters the gas station at 78231.35

Car 15673 enters the gas station at 78233.15

Car 15674 enters the gas station at 78237.09

Car 15675 enters the gas station at 78245.89

Car 15676 enters the gas station at 78247.22

Car 15677 enters the gas station at 78247.50

Car 15678 enters the gas station at 78267.56

Car 15679 enters the gas station at 78271.73

Car 15680 enters the gas station at 78278.49

Car 15681 enters the gas station at 78295.23

Car 15682 enters the gas station at 78301.63

Car 15683 enters the gas station at 78303.42

Car 15684 enters the gas station at 78303.88

Car 15685 enters the gas station at 78329.41

Car 15686 enters the gas station at 78333.32

Car 15687 enters the gas station at 78341.14

Car 15688 enters the gas station at 78343.80

Car 15689 enters the gas station at 78344.92

Car 15690 enters the gas station at 78345.20

Car 15691 enters the gas station at 78349.12

Car 15692 enters the gas station at 78360.11

Car 15693 enters the gas station at 78369.34

Car 15694 enters the gas station at 78369.61

Car 15695 enters the gas station at 78373.17

Car 15696 enters the gas station at 78376.70

Car 15697 enters the gas station at 78379.39

Car 15698 enters the gas station at 78380.02

Car 15699 enters the gas station at 78383.02

Car 15700 enters the gas station at 78387.14

Car 15701 enters the gas station at 78395.12

Car 15702 enters the gas station at 78399.36

Car 15703 enters the gas station at 78409.36

Car 15704 enters the gas station at 78423.41

Car 15705 enters the gas station at 78429.06

Car 15706 enters the gas station at 78432.51

Car 15707 enters the gas station at 78435.84

Car 15708 enters the gas station at 78450.28

Car 15709 enters the gas station at 78452.04

Car 15710 enters the gas station at 78452.30

Car 15711 enters the gas station at 78453.07

Car 15712 enters the gas station at 78465.50

Car 15713 enters the gas station at 78470.95

Car 15714 enters the gas station at 78471.21

Car 15715 enters the gas station at 78476.06

Car 15716 enters the gas station at 78487.27

Car 15717 enters the gas station at 78487.89

Car 15718 enters the gas station at 78490.03

Car 15719 enters the gas station at 78494.23

Car 15720 enters the gas station at 78498.51

Car 15721 enters the gas station at 78504.25

Car 15722 enters the gas station at 78522.95

Car 15723 enters the gas station at 78527.99

Car 15724 enters the gas station at 78529.65

Car 15725 enters the gas station at 78531.02

Car 15726 enters the gas station at 78537.37

Car 15727 enters the gas station at 78542.43

Car 15728 enters the gas station at 78545.68

Car 15729 enters the gas station at 78547.09

Car 15730 enters the gas station at 78549.31

Car 15731 enters the gas station at 78554.64

Car 15732 enters the gas station at 78560.87

Car 15733 enters the gas station at 78561.22

Car 15734 enters the gas station at 78562.01

Car 15735 enters the gas station at 78563.98

Car 15736 enters the gas station at 78571.24

Car 15737 enters the gas station at 78571.28

Car 15738 enters the gas station at 78575.84

Car 15739 enters the gas station at 78576.20

Car 15740 enters the gas station at 78582.18

Car 15741 enters the gas station at 78593.23

Car 15742 enters the gas station at 78593.73

Car 15743 enters the gas station at 78598.49

Car 15744 enters the gas station at 78612.93

Car 15745 enters the gas station at 78614.67

Car 15746 enters the gas station at 78615.91

Car 15747 enters the gas station at 78617.33

Car 15748 enters the gas station at 78623.05

Car 15749 enters the gas station at 78630.03

Car 15750 enters the gas station at 78636.66

Car 15751 enters the gas station at 78641.46

Car 15752 enters the gas station at 78645.55

Car 15753 enters the gas station at 78647.77

Car 15754 enters the gas station at 78661.93

Car 15755 enters the gas station at 78662.71

Car 15756 enters the gas station at 78669.61

Car 15757 enters the gas station at 78674.41

Car 15758 enters the gas station at 78685.45

Car 15759 enters the gas station at 78691.84

Car 15760 enters the gas station at 78692.03

Car 15761 enters the gas station at 78694.01

Car 15762 enters the gas station at 78695.28

Car 15763 enters the gas station at 78700.55

Car 15764 enters the gas station at 78703.65

Car 15765 enters the gas station at 78713.67

Car 15766 enters the gas station at 78720.29

Car 15767 enters the gas station at 78723.33

Car 15768 enters the gas station at 78725.13

Car 15769 enters the gas station at 78726.70

Car 15770 enters the gas station at 78729.48

Car 15771 enters the gas station at 78729.61

Car 15772 enters the gas station at 78730.41

Car 15773 enters the gas station at 78732.13

Car 15774 enters the gas station at 78736.97

Car 15775 enters the gas station at 78743.16

Car 15776 enters the gas station at 78751.19

Car 15777 enters the gas station at 78751.26

Car 15778 enters the gas station at 78752.11

Car 15779 enters the gas station at 78752.23

Car 15780 enters the gas station at 78755.96

Car 15781 enters the gas station at 78757.41

Car 15782 enters the gas station at 78761.95

Car 15783 enters the gas station at 78762.15

Car 15784 enters the gas station at 78768.71

Car 15785 enters the gas station at 78770.64

Car 15786 enters the gas station at 78784.24

Car 15787 enters the gas station at 78784.71

Car 15788 enters the gas station at 78785.08

Car 15789 enters the gas station at 78787.78

Car 15790 enters the gas station at 78792.60

Car 15791 enters the gas station at 78797.07

Car 15792 enters the gas station at 78799.06

Car 15793 enters the gas station at 78825.25

Car 15794 enters the gas station at 78838.37

Car 15795 enters the gas station at 78844.35

Car 15796 enters the gas station at 78847.95

Car 15797 enters the gas station at 78849.76

Car 15798 enters the gas station at 78860.97

Car 15799 enters the gas station at 78872.72

Car 15800 enters the gas station at 78874.07

Car 15801 enters the gas station at 78877.83

Car 15802 enters the gas station at 78880.21

Car 15803 enters the gas station at 78890.17

Car 15804 enters the gas station at 78907.35

Car 15805 enters the gas station at 78918.36

Car 15806 enters the gas station at 78919.93

Car 15807 enters the gas station at 78921.48

Car 15808 enters the gas station at 78923.37

Car 15809 enters the gas station at 78923.96

Car 15810 enters the gas station at 78926.70

Car 15811 enters the gas station at 78928.28

Car 15812 enters the gas station at 78940.05

Car 15813 enters the gas station at 78940.47

Car 15814 enters the gas station at 78941.16

Car 15815 enters the gas station at 78946.36

Car 15816 enters the gas station at 78949.18

Car 15817 enters the gas station at 78951.10

Car 15818 enters the gas station at 78958.32

Car 15819 enters the gas station at 78960.49

Car 15820 enters the gas station at 78962.90

Car 15821 enters the gas station at 78968.11

Car 15822 enters the gas station at 78971.64

Car 15823 enters the gas station at 78973.57

Car 15824 enters the gas station at 78983.49

Car 15825 enters the gas station at 78985.28

Car 15826 enters the gas station at 78988.50

Car 15827 enters the gas station at 78993.27

Car 15828 enters the gas station at 78995.02

Car 15829 enters the gas station at 79000.96

Car 15830 enters the gas station at 79008.12

Car 15831 enters the gas station at 79009.10

Car 15832 enters the gas station at 79009.97

Car 15833 enters the gas station at 79025.63

Car 15834 enters the gas station at 79033.41

Car 15835 enters the gas station at 79033.84

Car 15836 enters the gas station at 79036.42

Car 15837 enters the gas station at 79038.88

Car 15838 enters the gas station at 79055.44

Car 15839 enters the gas station at 79058.23

Car 15840 enters the gas station at 79060.78

Car 15841 enters the gas station at 79080.65

Car 15842 enters the gas station at 79088.54

Car 15843 enters the gas station at 79091.50

Car 15844 enters the gas station at 79092.78

Car 15845 enters the gas station at 79095.15

Car 15846 enters the gas station at 79099.96

Car 15847 enters the gas station at 79125.21

Car 15848 enters the gas station at 79137.31

Car 15849 enters the gas station at 79143.24

Car 15850 enters the gas station at 79144.30

Car 15851 enters the gas station at 79147.79

Car 15852 enters the gas station at 79148.16

Car 15853 enters the gas station at 79157.63

Car 15854 enters the gas station at 79165.89

Car 15855 enters the gas station at 79176.50

Car 15856 enters the gas station at 79177.92

Car 15857 enters the gas station at 79180.10

Car 15858 enters the gas station at 79184.44

Car 15859 enters the gas station at 79184.95

Car 15860 enters the gas station at 79185.80

Car 15861 enters the gas station at 79189.03

Car 15862 enters the gas station at 79206.19

Car 15863 enters the gas station at 79210.62

Car 15864 enters the gas station at 79212.74

Car 15865 enters the gas station at 79213.97

Car 15866 enters the gas station at 79219.43

Car 15867 enters the gas station at 79219.86

Car 15868 enters the gas station at 79226.39

Car 15869 enters the gas station at 79230.26

Car 15870 enters the gas station at 79234.62

Car 15871 enters the gas station at 79259.41

Car 15872 enters the gas station at 79267.85

Car 15873 enters the gas station at 79269.47

Car 15874 enters the gas station at 79271.74

Car 15875 enters the gas station at 79274.45

Car 15876 enters the gas station at 79275.02

Car 15877 enters the gas station at 79276.59

Car 15878 enters the gas station at 79283.61

Car 15879 enters the gas station at 79286.27

Car 15880 enters the gas station at 79286.82

Car 15881 enters the gas station at 79291.17

Car 15882 enters the gas station at 79302.54

Car 15883 enters the gas station at 79309.44

Car 15884 enters the gas station at 79322.10

Car 15885 enters the gas station at 79323.75

Car 15886 enters the gas station at 79333.82

Car 15887 enters the gas station at 79343.38

Car 15888 enters the gas station at 79345.20

Car 15889 enters the gas station at 79347.03

Car 15890 enters the gas station at 79351.68

Car 15891 enters the gas station at 79354.26

Car 15892 enters the gas station at 79355.33

Car 15893 enters the gas station at 79360.05

Car 15894 enters the gas station at 79362.52

Car 15895 enters the gas station at 79381.73

Car 15896 enters the gas station at 79385.71

Car 15897 enters the gas station at 79386.77

Car 15898 enters the gas station at 79390.69

Car 15899 enters the gas station at 79391.19

Car 15900 enters the gas station at 79391.28

Car 15901 enters the gas station at 79397.07

Car 15902 enters the gas station at 79398.80

Car 15903 enters the gas station at 79407.87

Car 15904 enters the gas station at 79423.76

Car 15905 enters the gas station at 79425.43

Car 15906 enters the gas station at 79430.86

Car 15907 enters the gas station at 79431.61

Car 15908 enters the gas station at 79432.15

Car 15909 enters the gas station at 79450.75

Car 15910 enters the gas station at 79451.77

Car 15911 enters the gas station at 79465.17

Car 15912 enters the gas station at 79471.02

Car 15913 enters the gas station at 79474.42

Car 15914 enters the gas station at 79480.27

Car 15915 enters the gas station at 79493.07

Car 15916 enters the gas station at 79494.17

Car 15917 enters the gas station at 79495.22

Car 15918 enters the gas station at 79497.36

Car 15919 enters the gas station at 79506.86

Car 15920 enters the gas station at 79510.86

Car 15921 enters the gas station at 79511.44

Car 15922 enters the gas station at 79518.39

Car 15923 enters the gas station at 79532.34

Car 15924 enters the gas station at 79532.80

Car 15925 enters the gas station at 79547.96

Car 15926 enters the gas station at 79550.03

Car 15927 enters the gas station at 79563.59

Car 15928 enters the gas station at 79565.93

Car 15929 enters the gas station at 79569.84

Car 15930 enters the gas station at 79574.47

Car 15931 enters the gas station at 79581.74

Car 15932 enters the gas station at 79593.15

Car 15933 enters the gas station at 79597.44

Car 15934 enters the gas station at 79604.96

Car 15935 enters the gas station at 79607.93

Car 15936 enters the gas station at 79642.28

Car 15937 enters the gas station at 79643.91

Car 15938 enters the gas station at 79646.19

Car 15939 enters the gas station at 79659.45

Car 15940 enters the gas station at 79667.58

Car 15941 enters the gas station at 79671.25

Car 15942 enters the gas station at 79672.81

Car 15943 enters the gas station at 79674.02

Car 15944 enters the gas station at 79677.64

Car 15945 enters the gas station at 79683.84

Car 15946 enters the gas station at 79684.55

Car 15947 enters the gas station at 79690.87

Car 15948 enters the gas station at 79691.19

Car 15949 enters the gas station at 79692.50

Car 15950 enters the gas station at 79697.70

Car 15951 enters the gas station at 79703.49

Car 15952 enters the gas station at 79713.23

Car 15953 enters the gas station at 79718.62

Car 15954 enters the gas station at 79718.77

Car 15955 enters the gas station at 79725.05

Car 15956 enters the gas station at 79726.51

Car 15957 enters the gas station at 79738.62

Car 15958 enters the gas station at 79743.33

Car 15959 enters the gas station at 79749.91

Car 15960 enters the gas station at 79752.84

Car 15961 enters the gas station at 79758.78

Car 15962 enters the gas station at 79768.22

Car 15963 enters the gas station at 79779.13

Car 15964 enters the gas station at 79786.20

Car 15965 enters the gas station at 79787.55

Car 15966 enters the gas station at 79799.05

Car 15967 enters the gas station at 79808.90

Car 15968 enters the gas station at 79810.77

Car 15969 enters the gas station at 79814.11

Car 15970 enters the gas station at 79819.96

Car 15971 enters the gas station at 79829.84

Car 15972 enters the gas station at 79837.98

Car 15973 enters the gas station at 79847.48

Car 15974 enters the gas station at 79848.27

Car 15975 enters the gas station at 79851.09

Car 15976 enters the gas station at 79853.95

Car 15977 enters the gas station at 79870.22

Car 15978 enters the gas station at 79881.16

Car 15979 enters the gas station at 79882.53

Car 15980 enters the gas station at 79883.46

Car 15981 enters the gas station at 79904.63

Car 15982 enters the gas station at 79908.22

Car 15983 enters the gas station at 79911.87

Car 15984 enters the gas station at 79912.90

Car 15985 enters the gas station at 79920.60

Car 15986 enters the gas station at 79923.06

Car 15987 enters the gas station at 79938.92

Car 15988 enters the gas station at 79941.41

Car 15989 enters the gas station at 79945.79

Car 15990 enters the gas station at 79949.12

Car 15991 enters the gas station at 79951.18

Car 15992 enters the gas station at 79953.17

Car 15993 enters the gas station at 79966.81

Car 15994 enters the gas station at 79968.11

Car 15995 enters the gas station at 79968.25

Car 15996 enters the gas station at 79976.98

Car 15997 enters the gas station at 79981.80

Car 15998 enters the gas station at 79993.27

Car 15999 enters the gas station at 79998.86

Car 16000 enters the gas station at 80001.25

Car 16001 enters the gas station at 80006.49

Car 16002 enters the gas station at 80007.76

Car 16003 enters the gas station at 80024.76

Car 16004 enters the gas station at 80028.88

Car 16005 enters the gas station at 80030.25

Car 16006 enters the gas station at 80037.23

Car 16007 enters the gas station at 80040.27

Car 16008 enters the gas station at 80041.70

Car 16009 enters the gas station at 80046.49

Car 16010 enters the gas station at 80048.05

Car 16011 enters the gas station at 80052.92

Car 16012 enters the gas station at 80053.21

Car 16013 enters the gas station at 80054.14

Car 16014 enters the gas station at 80055.34

Car 16015 enters the gas station at 80061.15

Car 16016 enters the gas station at 80075.40

Car 16017 enters the gas station at 80087.51


KeyboardInterrupt: ignored

In [ ]:
sorted([2, 3, 4, 2, 8, 9, 10, 1, 6, 5])

[1, 2, 2, 3, 4, 5, 6, 8, 9, 10]

# RUNNING CHAT GPT EXAMPLE CODE 2

In [ ]:
import simpy

GAS_STATION_SIZE = 2  # Number of refill points
TANK_SIZE = 40  # Size of car's fuel tank
REFUEL_SPEED = 2  # Litres of fuel per second
# ARRIVAL_TIMES =  [1, 2, 2, 3, 4, 5, 6, 8, 9, 10] # Arrival times for each car
ARRIVAL_TIMES =  [1, 1, 0, 1, 1, 1, 1, 2, 1, 1] # Arrival times for each car
REFILL_TIMES = [1, 2, 1, 2, 1, 2, 1, 2, 1, 2]  # Refill time for each car
SIM_TIME = sum(ARRIVAL_TIMES) + max(REFILL_TIMES)  # Simulation time in seconds

def car(env, name, gas_station, fuel_pump, refill_time):
    print(f'\n{name} enters the gas station at {env.now:.2f}')
    with gas_station.request() as req:
        yield req

        print(f'{name} starts refueling at {env.now:.2f}')
        
        # yield fuel_pump.get(TANK_SIZE)
        
        yield env.timeout(refill_time)
        print(f'{name} finishes refueling at {env.now:.2f}')

    print(f'{name} exits the gas station at {env.now:.2f} -------------------------------------------')

def car_generator(env, gas_station, fuel_pump, arrival_times, refill_times):
    for i, arrival_time in enumerate(arrival_times):
        yield env.timeout(arrival_time)
        env.process(car(env, f'Car {i+1}', gas_station, fuel_pump, refill_times[i]))
        

# Create the SimPy environment
env = simpy.Environment()

# Create the gas station and fuel pumps
gas_station = simpy.Resource(env, capacity=GAS_STATION_SIZE)
fuel_pump = simpy.Container(env, init=GAS_STATION_SIZE*TANK_SIZE, capacity=GAS_STATION_SIZE*TANK_SIZE)

# Start the simulation
env.process(car_generator(env, gas_station, fuel_pump, ARRIVAL_TIMES, REFILL_TIMES))

In [ ]:
env.run(until=8)

Car 6 finishes refueling at 7.00
Car 6 exits the gas station at 7.00 -------------------------------------------
Car 7 finishes refueling at 7.00
Car 7 exits the gas station at 7.00 -------------------------------------------

In [ ]:
env.run()

Car 1 enters the gas station at 1.00
Car 1 starts refueling at 1.00

Car 2 enters the gas station at 2.00
Car 1 finishes refueling at 2.00
Car 1 exits the gas station at 2.00 -------------------------------------------

Car 3 enters the gas station at 2.00
Car 2 starts refueling at 2.00
Car 3 starts refueling at 2.00

Car 4 enters the gas station at 3.00
Car 3 finishes refueling at 3.00
Car 3 exits the gas station at 3.00 -------------------------------------------
Car 4 starts refueling at 3.00
Car 2 finishes refueling at 4.00
Car 2 exits the gas station at 4.00 -------------------------------------------

Car 5 enters the gas station at 4.00
Car 5 starts refueling at 4.00
Car 4 finishes refueling at 5.00
Car 4 exits the gas station at 5.00 -------------------------------------------

Car 6 enters the gas station at 5.00
Car 5 finishes refueling at 5.00
Car 5 exits the gas station at 5.00 -------------------------------------------
Car 6 starts refueling at 5.00

Car 7 enters the gas station at 6.00
Car 7 starts refueling at 6.00
Car 6 finishes refueling at 7.00
Car 6 exits the gas station at 7.00 -------------------------------------------
Car 7 finishes refueling at 7.00
Car 7 exits the gas station at 7.00 -------------------------------------------

Car 8 enters the gas station at 8.00
Car 8 starts refueling at 8.00

Car 9 enters the gas station at 9.00
Car 9 starts refueling at 9.00
Car 8 finishes refueling at 10.00
Car 8 exits the gas station at 10.00 -------------------------------------------

Car 10 enters the gas station at 10.00
Car 9 finishes refueling at 10.00
Car 9 exits the gas station at 10.00 -------------------------------------------
Car 10 starts refueling at 10.00
Car 10 finishes refueling at 12.00
Car 10 exits the gas station at 12.00 -------------------------------------------

In [ ]:
ARRIVAL_TIMES =  [1, 1, 0, 1, 1, 1, 1, 2, 1, 1] # Arrival times for each car
REFILL_TIMES = [1, 2, 1, 2, 1, 2, 1, 2]  # Refill time for each car
for i, arrival_time in enumerate(ARRIVAL_TIMES):
  print(i, arrival_time)
  print(i, arrival_time, REFILL_TIMES[i])

0 1
0 1 1
1 1
1 1 2
2 0
2 0 1
3 1
3 1 2
4 1
4 1 1
5 1
5 1 2
6 1
6 1 1
7 2
7 2 2
8 1

IndexError: ignored

In [ ]:
ARRIVAL_TIMES =  [1, 1, 0, 1, 1, 1, 1, 2, 1, 1] # Arrival times for each car
REFILL_TIMES = [1, 2, 1, 2, 1, 2, 1, 2, 1, 2]  # Refill time for each car
SIM_TIME = sum(ARRIVAL_TIMES) + max(REFILL_TIMES)  # Simulation time in seconds
print(SIM_TIME)

12

# TRYING SIMPY ON THE DATASET

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_pickle('/content/drive/MyDrive/aepr/data_preprocessed.pkl')

In [ ]:
# data.sort_values(by='order_place', axis=0, ascending=True, inplace=True, kind='quicksort', na_position='last')

In [ ]:
# data.to_pickle('/content/drive/MyDrive/aepr/data_preprocessed.pkl')

In [ ]:
data

,ID,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Time_taken(min),order_pick,order_place,order_delivered
0,0xd300,9.970717,76.285447,10.030717,76.345447,11-02-2022,00:00:00,00:05:00,27,2022-02-11 00:05:00,2022-02-11 00:00:00,2022-02-11 00:50:00
1,0xc614,30.340722,78.060221,30.370722,78.090221,11-02-2022,00:00:00,00:10:00,11,2022-02-11 00:10:00,2022-02-11 00:00:00,2022-02-11 00:55:00
2,0xd152,23.234249,77.434007,23.294249,77.494007,11-02-2022,00:00:00,00:10:00,17,2022-02-11 00:10:00,2022-02-11 00:00:00,2022-02-11 00:55:00
3,0xc401,30.893081,75.821495,30.943081,75.871495,11-02-2022,00:00:00,00:05:00,12,2022-02-11 00:05:00,2022-02-11 00:00:00,2022-02-11 00:50:00
4,0xcb30,27.160934,78.044095,27.170934,78.054095,11-02-2022,08:10:00,08:20:00,27,2022-02-11 08:20:00,2022-02-11 08:10:00,2022-02-11 09:05:00
...,...,...,...,...,...,...,...,...,...,...,...,...
43857,0x8fb5,26.905287,75.794592,27.045287,75.934592,06-04-2022,23:55:00,00:05:00,28,2022-04-06 00:05:00,2022-04-06 23:55:00,2022-04-06 00:50:00
43858,0xb7ff,12.978453,77.643685,13.088453,77.753685,06-04-2022,23:55:00,00:00:00,40,2022-04-06 00:00:00,2022-04-06 23:55:00,2022-04-06 00:45:00
43859,0x98f1,21.175975,72.795503,21.255975,72.875503,06-04-2022,23:55:00,00:05:00,35,2022-04-06 00:05:00,2022-04-06 23:55:00,2022-04-06 00:50:00
43860,0x6b08,13.026279,80.174568,13.096279,80.244568,06-04-2022,23:55:00,00:00:00,42,2022-04-06 00:00:00,2022-04-06 23:55:00,2022-04-06 00:45:00
43861,0x8b6f,12.284747,76.625861,12.364747,76.705861,06-04-2022,23:55:00,00:00:00,24,2022-04-06 00:00:00,2022-04-06 23:55:00,2022-04-06 00:45:00

In [ ]:
# We don't need to worry if there are some free times in the day, for e.g. there are almost no orders from 2 am to 8 am in the morning. This is no 
# worry, because anyways to cater to the needs of the customers, the restaurants can ask the drivers to stay longer, clear the traffic, then basically
# in the simulation, all the bikers will be ideal from 2 am to 8 am. But the results that we will plot will be based on the wait time for the customers 
# and not the actual times.
type(data['order_place'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
list(data['order_place'])

In [ ]:
a = list(range(1,11))

with open('data_order_place.txt', 'w') as f:
  # f.write(str(a))
  output_string = str(list(data['order_place']))
  output_string = output_string.replace(',', '\n')
  f.write(output_string)

In [ ]:
print('$\n$')
print('a')

$
$
a

In [ ]:
import geopy.distance

coords_1 = (52.2296756, 21.0122287)
coords_2 = (52.406374, 16.9251681)

print(geopy.distance.geodesic(coords_1, coords_2).km)

279.35290160430094

In [ ]:
def dist(lat1, long1, lat2, long2):
  # returns the distance between two points by 
  # shortest distance on surface of earth
  return geopy.distance.geodesic((lat1, long1), (lat2, long2)).km

In [ ]:
def man_dist(lat1, long1, lat2, long2):
  return dist(lat1, long1, lat2, long1) + dist(lat2, long1, lat2, long2)

In [ ]:
# SIMULATION PARAMETERS
MAX_LAT = max(data['Restaurant_latitude'].max(), data['Delivery_location_latitude'].max())
MIN_LAT = min(data['Restaurant_latitude'].min(), data['Delivery_location_latitude'].min())

MAX_LONG = max(data['Restaurant_longitude'].max(), data['Delivery_location_longitude'].max())
MIN_LONG = min(data['Restaurant_longitude'].min(), data['Delivery_location_longitude'].min())

NUM_BOYS = 50
NUM_BOYS_PER_RESTRO = 5
BIKE_SPEED = 40

print((MAX_LAT, MIN_LONG))
print((MAX_LAT, MAX_LONG))
print((MIN_LAT, MIN_LONG))
print((MIN_LAT, MAX_LONG))

# (31, 0), (31, 88), (-30, 0.0), (-30, 88)

(31.054057, 0.0)
(31.054057, 88.563452)
(-30.902872, 0.0)
(-30.902872, 88.563452)

In [ ]:
from random import randrange
boys = []

for i in range(NUM_BOYS):
  boys.append({'lat':randrange(10001), 'long':randrange(10001)})

for i in range(NUM_BOYS):
  boys[i]['lat'] = MIN_LAT + (MAX_LAT - MIN_LAT)*boys[i]['lat']/10000
  boys[i]['long'] = MIN_LONG + (MAX_LONG - MIN_LONG)*boys[i]['long']/10000

In [ ]:
boys

[{'lat': 30.979708685200006, 'long': 82.87767838159999},
 {'lat': -1.5786575043000006, 'long': 24.824335595599997},
 {'lat': -10.450889737099999, 'long': 32.6622010976},
 {'lat': -9.341860707999999, 'long': 22.0257305124},
 {'lat': -2.879753013299993, 'long': 32.2725219088},
 {'lat': -19.1186641042, 'long': 88.1029220496},
 {'lat': 29.424589767299995, 'long': 64.42991133},
 {'lat': 23.074004544800008, 'long': 42.156203152},
 {'lat': -25.401096704799997, 'long': 14.5066934376},
 {'lat': -22.1359665465, 'long': 69.1946250476},
 {'lat': 30.831012055600002, 'long': 4.5344487423999995},
 {'lat': -12.637969330799997, 'long': 45.8670117908},
 {'lat': -26.627843899, 'long': 13.771616786},
 {'lat': -20.667587329199996, 'long': 23.132773662399998},
 {'lat': 0.026026956800002665, 'long': 58.974402686800005},
 {'lat': 10.930446460800002, 'long': 88.0940657044},
 {'lat': -25.3329440829, 'long': 86.9958788996},
 {'lat': 6.0916103059000015, 'long': 65.3066895048},
 {'lat': -1.3184384025, 'long': 0.6553695448},
 {'lat': 30.967317299399998, 'long': 15.365758922},
 {'lat': 10.750771366700004, 'long': 77.2538991796},
 {'lat': 8.495539151100001, 'long': 67.4587813884},
 {'lat': -29.626559262599997, 'long': 13.514782775199999},
 {'lat': -3.920629420499999, 'long': 67.49420676919999},
 {'lat': 2.869849997900001, 'long': 38.4011127872},
 {'lat': -19.186816726099998, 'long': 5.7831934155999996},
 {'lat': -15.289725891999998, 'long': 79.6008306576},
 {'lat': -12.6193822521, 'long': 63.1191722404},
 {'lat': 10.131202076700003, 'long': 24.0804025988},
 {'lat': 5.626933338400004, 'long': 8.4400969756},
 {'lat': -18.6168129793, 'long': 88.1029220496},
 {'lat': 16.060480182000003, 'long': 80.7432991884},
 {'lat': -12.743296110099998, 'long': 24.372661990399997},
 {'lat': 3.3593097370000002, 'long': 79.5831179672},
 {'lat': -11.2811125857, 'long': 17.1724533428},
 {'lat': 8.167167427400006, 'long': 23.7615741716},
 {'lat': -7.842503026199996, 'long': 15.339189886399998},
 {'lat': 9.300979228100008, 'long': 76.1468560296},
 {'lat': -24.589460934899996, 'long': 23.7881432072},
 {'lat': 16.196785425800005, 'long': 2.1786609192},
 {'lat': 14.963842538700003, 'long': 25.5859812828},
 {'lat': -10.4075198868, 'long': 10.583332514},
 {'lat': -29.434492782699998, 'long': 59.408363601599994},
 {'lat': 21.748126264200007, 'long': 27.9329127608},
 {'lat': 21.624212406200005, 'long': 16.2691061324},
 {'lat': 3.830182397400005, 'long': 43.8477650852},
 {'lat': 9.697503573700008, 'long': 15.1354939468},
 {'lat': 18.408647791099998, 'long': 82.4171484312},
 {'lat': 9.629350951800003, 'long': 14.5421188184},
 {'lat': -13.808955288899998, 'long': 69.2743321544}]

# CHAT GPT CODE

In [ ]:
%pip install simpy
import pandas as pd
data = pd.read_pickle('/content/drive/MyDrive/aepr/data_preprocessed.pkl')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: simpy in /usr/local/lib/python3.10/dist-packages (4.0.1)

In [ ]:
# %pip install simpy

import pandas as pd
data = pd.read_pickle('/content/drive/MyDrive/aepr/data_preprocessed.pkl')

import random
from geopy.distance import geodesic
import simpy

# Constants
NUM_CABS = 5
NUM_BOYS = NUM_CABS
SIM_TIME = 120
CITY_COORDS = [(31, 0), (31, 88), (-30, 0.0), (-30, 88)]  # Coordinates of the corners of the city
# BOOKINGS = [(5, (31, 50), (20, 40)), (10, (20, 10), (-10, 20)), (15, (10, 20), (5, 60)),
#             (20, (0, 0), (-20, -20)), (25, (-10, 50), (10, 70)), (30, (-20, 20), (-30, 50)),
#             (35, (-20, 10), (-30, 0)), (40, (-5, 10), (-15, 30)), (45, (20, 40), (0, 60)),
#             (50, (5, 30), (-5, 70)), (55, (10, 40), (-5, 50)), (60, (-5, 20), (15, 40)),
#             (65, (-15, 50), (-5, 30)), (70, (20, 60), (5, 20)), (75, (30, 70), (-10, 50)),
#             (80, (-20, 0), (10, 30)), (85, (0, 50), (20, 20)), (90, (-10, 0), (20, 50)),
#             (95, (10, 60), (0, 10)), (100, (-30, 20), (0, 0))]

BOOKINGS = [(5, (31, 50), (20, 40)), (10, (20, 10), (-10, 20)), (15, (10, 20), (5, 60)),
            (20, (0, 0), (-20, -20)), (25, (-10, 50), (10, 70)), (30, (-20, 20), (-30, 50)),
            (35, (-20, 10), (-30, 0)), (40, (-5, 10), (-15, 30)), (45, (20, 40), (0, 60)),
            (50, (5, 30), (-5, 70)), (55, (10, 40), (-5, 50)), (60, (-5, 20), (15, 40)),
            (65, (-15, 50), (-5, 30)), (70, (20, 60), (5, 20)), (75, (30, 70), (-10, 50)),
            (80, (-20, 0), (10, 30)), (85, (0, 50), (20, 20)), (90, (-10, 0), (20, 50)),
            (95, (10, 60), (0, 10)), (100, (-30, 20), (0, 0))]

BOOKINGS = [(5, booking[1], booking[2]) for booking in BOOKINGS]

MAX_LAT = max(data['Restaurant_latitude'].max(), data['Delivery_location_latitude'].max())
MIN_LAT = min(data['Restaurant_latitude'].min(), data['Delivery_location_latitude'].min())

MAX_LONG = max(data['Restaurant_longitude'].max(), data['Delivery_location_longitude'].max())
MIN_LONG = min(data['Restaurant_longitude'].min(), data['Delivery_location_longitude'].min())


NUM_BOYS_PER_RESTRO = 5
BIKE_SPEED = 30

# Classes
class Cab:
    def __init__(self, env, id):
        self.env = env
        self.id = id
        self.location = self.get_random_location()
        self.status = "available"
        self.end_time = 0
        
    def get_random_location(self):
        lat = random.randrange(10001)
        long = random.randrange(10001)
        lat = MIN_LAT + (MAX_LAT - MIN_LAT)*lat/10000
        long = MIN_LONG + (MAX_LONG - MIN_LONG)*long/10000
        return (lat,long)
        # GADBAD
    
    def move_to(self, dest):
        '''GADBAD put status as unavailable'''
        distance = geodesic(self.location, dest).km
        time = distance / BIKE_SPEED * 60  # 30 km/hr is the speed of the cab
        yield self.env.timeout(time)
        self.location = dest
        
class Customer:
    def __init__(self, env, id, pickup, dropoff):
        self.env = env
        self.id = id
        self.pickup = pickup
        self.dropoff = dropoff
        self.start_time = env.now
        self.wait_time = None
        self.cab = None
        self.real_wait_time = None
        
    def request_cab(self, cabs, arrival_time):
      print(f'request cab function called for Customer #{self.id} at time {self.env.now}')
      yield env.timeout(arrival_time)
      print(f'Customer #{self.id} actually arrives at time {self.env.now}')
      with cabs.request() as req:
            yield req
            cab = self.find_nearest_cab(cabs)
            if cab is not None:
                self.cab = cab
                cab.status = "occupied"
                yield self.env.process(cab.move_to(self.pickup))
                yield self.env.process(cab.move_to(self.dropoff))
                cab.status = "available"
                cab.end_time = self.env.now
                self.wait_time = cab.end_time - self.start_time
                self.real_wait_time = self.wait_time - geodesic(self.pickup, self.dropoff).km / BIKE_SPEED * 60
            else:
                print('>>> FIND_NEAREST_CAB RETURNED None as the output <<<')
                
    def find_nearest_cab(self, cabs):
        nearest_cab = None
        nearest_distance = float("inf")
        for cab in cabs.users:
            if cab.status == "available":
                distance = geodesic(cab.location, self.pickup).km
                if distance < nearest_distance:
                    nearest_cab = cab
                    nearest_distance = distance
        return nearest_cab
    
# Setup and start the simulation
def setup(env, bookings, cabs):
    # Create cabs
    for i in range(NUM_CABS):
        cab = Cab(env, i)
        cabs.put(cab)

    # Create customers
    for id, booking in enumerate(bookings):
        arrival_time, pickup, dropoff = booking
        customer = Customer(env, id, pickup, dropoff)
        env.process(customer.request_cab(cabs, arrival_time))

# Run the simulation
env = simpy.Environment()
cabs = simpy.Resource(env, capacity=NUM_CABS)
env.process(setup(env, BOOKINGS, cabs))
env.run(until=SIM_TIME)

# Print results
for id, booking in enumerate(BOOKINGS):
    # arrival_time, pickup, dropoff = booking
    customer = next((c for c in Customer if c.id == id), None)
    if customer is not None:
        print(f"Customer {id} waited {customer.wait_time:.2f} minutes for a cab.")
    else:
        print(f"Customer {id} did not get a cab.")

TypeError: ignored

In [ ]:
# BOOKINGS = [(5, (31, 50), (20, 40)), (10, (20, 10), (-10, 20)), (15, (10, 20), (5, 60)),
#             (20, (0, 0), (-20, -20)), (25, (-10, 50), (10, 70)), (30, (-20, 20), (-30, 50)),
#             (35, (-20, 10), (-30, 0)), (40, (-5, 10), (-15, 30)), (45, (20, 40), (0, 60)),
#             (50, (5, 30), (-5, 70)), (55, (10, 40), (-5, 50)), (60, (-5, 20), (15, 40)),
#             (65, (-15, 50), (-5, 30)), (70, (20, 60), (5, 20)), (75, (30, 70), (-10, 50)),
#             (80, (-20, 0), (10, 30)), (85, (0, 50), (20, 20)), (90, (-10, 0), (20, 50)),
#             (95, (10, 60), (0, 10)), (100, (-30, 20), (0, 0))]
# for i in BOOKINGS:
#   print(i)
            
# BOOKINGS = [(5, booking[1], booking[2]) for booking in BOOKINGS]

(5, (31, 50), (20, 40))
(10, (20, 10), (-10, 20))
(15, (10, 20), (5, 60))
(20, (0, 0), (-20, -20))
(25, (-10, 50), (10, 70))
(30, (-20, 20), (-30, 50))
(35, (-20, 10), (-30, 0))
(40, (-5, 10), (-15, 30))
(45, (20, 40), (0, 60))
(50, (5, 30), (-5, 70))
(55, (10, 40), (-5, 50))
(60, (-5, 20), (15, 40))
(65, (-15, 50), (-5, 30))
(70, (20, 60), (5, 20))
(75, (30, 70), (-10, 50))
(80, (-20, 0), (10, 30))
(85, (0, 50), (20, 20))
(90, (-10, 0), (20, 50))
(95, (10, 60), (0, 10))
(100, (-30, 20), (0, 0))

In [ ]:
import random
CITY_COORDS = [(31, 0), (31, 88), (-30, 0.0), (-30, 88)]  # Coordinates of the corners of the city
for i in range(10):
  print(random.choice(CITY_COORDS))

(31, 0)
(31, 88)
(-30, 88)
(31, 88)
(-30, 88)
(31, 88)
(31, 0)
(-30, 0.0)
(-30, 88)
(31, 88)

### ONE MORE FRESH START

In [44]:
import pandas as pd
data = pd.read_pickle('data_preprocessed.pkl')

In [45]:
data.shape

(43862, 12)

In [46]:
data.head(10)

,ID,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Time_taken(min),order_pick,order_place,order_delivered
0,0xc801,19.875908,75.358888,19.935908,75.418888,11-02-2022,23:45:00,00:00:00,29,2022-02-11 00:00:00,2022-02-11 23:45:00,2022-02-11 00:45:00
1,0xe188,23.264015,77.408236,23.294015,77.438236,11-02-2022,23:50:00,00:00:00,19,2022-02-11 00:00:00,2022-02-11 23:50:00,2022-02-11 00:45:00
2,0xd7cf,0.000000,0.000000,0.030000,0.030000,11-02-2022,23:50:00,00:00:00,15,2022-02-11 00:00:00,2022-02-11 23:50:00,2022-02-11 00:45:00
3,0xcf54,10.027364,76.308258,10.057364,76.338258,11-02-2022,23:50:00,00:00:00,21,2022-02-11 00:00:00,2022-02-11 23:50:00,2022-02-11 00:45:00
4,0xe256,30.892860,75.822199,30.942860,75.872199,11-02-2022,23:55:00,00:00:00,32,2022-02-11 00:00:00,2022-02-11 23:55:00,2022-02-11 00:45:00
5,0xd70b,23.232537,77.429845,23.282537,77.479845,11-02-2022,23:55:00,00:00:00,22,2022-02-11 00:00:00,2022-02-11 23:55:00,2022-02-11 00:45:00
6,0xd204,30.885814,75.786976,30.915814,75.816976,11-02-2022,23:55:00,00:00:00,19,2022-02-11 00:00:00,2022-02-11 23:55:00,2022-02-11 00:45:00
7,0xd8f2,22.569367,88.433187,22.619367,88.483187,11-02-2022,23:55:00,00:00:00,26,2022-02-11 00:00:00,2022-02-11 23:55:00,2022-02-11 00:45:00
8,0xc9dd,25.451517,81.832616,25.501517,81.882616,11-02-2022,23:55:00,00:00:00,19,2022-02-11 00:00:00,2022-02-11 23:55:00,2022-02-11 00:45:00
9,0xe093,22.537960,88.349843,22.567960,88.379843,11-02-2022,23:50:00,00:05:00,17,2022-02-11 00:05:00,2022-02-11 23:50:00,2022-02-11 00:50:00

In [47]:
data.head(10).shape

(10, 12)

In [48]:
# data.to_pickle('/content/drive/MyDrive/aepr/data_preprocessed.pkl')
data.sort_values(by='order_pick', axis=0, ascending=True, inplace=True, kind='quicksort', na_position='last', ignore_index=True)

list1 = [i for i in range(0,100,10)]
data1 = data.iloc[list1]
data1.reset_index(inplace=True)
data1.to_pickle('data_10.pkl')

list1 = [i for i in range(0,1000,10)]
data1 = data.iloc[list1]
data1.reset_index(inplace=True)
data1.to_pickle('data_100.pkl')

list1 = [i for i in range(0,10000,10)]
data1 = data.iloc[list1]
data1.reset_index(inplace=True)
data1.to_pickle('data_1000.pkl')

data.to_pickle('data_preprocessed.pkl')

In [34]:
for i,j in enumerate(data.head(10)):
    print(j)

ID
Restaurant_latitude
Restaurant_longitude
Delivery_location_latitude
Delivery_location_longitude
Order_Date
Time_Orderd
Time_Order_picked
Time_taken(min)
order_pick
order_place
order_delivered

In [32]:
list(dir(data['order_pick'][100] - data['order_pick'][0]))

['__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pyx_vtable__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_cython__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setstate__',
 '__setstate_cython__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_creso',
 '_d',
 '_from_value_and_reso',
 '_h',
 '_is_populated',
 '_m',
 '_maybe_cast_to_matching_resos',
 '_ms',
 '_ns',
 '_repr_base',
 '_req_any_kwargs_new',
 '_round',
 '_s',
 '_unit',
 '_us',
 '_value',
 'as_unit',
 'asm8',
 'ceil',
 'components',
 'days',
 'floor',
 'isoformat',
 'max',
 'microseconds',
 'min',
 'nanoseconds',
 'resolution',
 'resolution_string',
 'round',
 'seconds',
 'to_numpy',
 'to_pytimedelta',
 'to_timedelta64',
 'total_seconds',
 'unit',
 'value',
 'view']

In [33]:
# (data['order_pick'][100] - data['order_pick'][0]).min
(data['order_pick'][100] - data['order_pick'][0])

Timedelta('0 days 09:25:00')